name: interview

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: set up python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install requests
    
      - name: run pylint
        run: pylint *.py

  codeQl:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: python
          build-mode: none

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
    
  uploadArtifact:
      needs: [lint, codeQl]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/upload_artifact@v4
          with:
            name: player_roster

            path: ./player_roster.json

            if-no-files-found: error 
            
            overwrite: true




    

    
  
