name: interview

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3

      - name: install pylint dependencies
        run: pip install pylint
    
      - name: run pylint
        run: pylint *.py
    
    

    

    
  
