name: interview

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: set up python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install pylint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint      
    
      - name: run pylint
        run: pylint *.py

  codeQl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run codeQL
      uses: actions/codeql-action@v3
    
    

    

    
  
